# Locate LLVM

IF(NOT LLVM_REQUIRED_COMPONENTS)
	SET(LLVM_REQUIRED_COMPONENTS core support option transformutils mcparser bitreader)
ENDIF(NOT LLVM_REQUIRED_COMPONENTS)

MACRO(LLVM_CONFIG OUTPUT_VARIABLE WHAT)
	MESSAGE("${LLVM_CONFIG_EXECUTABLE} --${WHAT} ${ARGN}")
	execute_process(COMMAND ${LLVM_CONFIG_EXECUTABLE} "--${WHAT}" ${ARGN} OUTPUT_VARIABLE ${OUTPUT_VARIABLE} OUTPUT_STRIP_TRAILING_WHITESPACE)
ENDMACRO()

IF(NOT LLVM_ROOT)
	file(GLOB LLVM_CONFIG_EXECUTABLE_GLOB /usr/bin/llvm-config-3.?)
	list(SORT LLVM_CONFIG_EXECUTABLE_GLOB)
	list(REVERSE LLVM_CONFIG_EXECUTABLE_GLOB)
	list(GET LLVM_CONFIG_EXECUTABLE_GLOB 0 LLVM_CONFIG_EXECUTABLE)

	LLVM_CONFIG(LLVM_ROOT prefix)

	IF(LLVM_ROOT)
		MESSAGE("Found LLVM_ROOT at: " ${LLVM_ROOT})
	ELSE(LLVM_ROOT)
		MESSAGE(SEND_ERROR "Failed to find LLVM_ROOT")
	ENDIF(LLVM_ROOT)
	
ELSE(NOT LLVM_ROOT)
	find_program(LLVM_CONFIG_EXECUTABLE
		NAMES llvm-config
		PATHS ${LLVM_ROOT}
		PATH_SUFFIXES bin
		NO_DEFAULT_PATH
	)
	
	MESSAGE("Found llvm-config at: " ${LLVM_CONFIG_EXECUTABLE})
ENDIF(NOT LLVM_ROOT)

IF(NOT LLVM_CONFIG_EXECUTABLE)
	MESSAGE(SEND_ERROR "Unable to find llvm-config executable...")
ENDIF(NOT LLVM_CONFIG_EXECUTABLE)

LLVM_CONFIG(LLVM_VERSION version)

IF(NOT LLVM_VERSION)
	MESSAGE(SEND_ERROR "Unable to find llvm version...")
ENDIF(NOT LLVM_VERSION)

LLVM_CONFIG(LLVM_LDFLAGS ldflags)
LLVM_CONFIG(LLVM_CFLAGS cflags)
LLVM_CONFIG(LLVM_LIBS libs ${LLVM_REQUIRED_COMPONENTS})

SET(LLVM_LIBS "-lclangFrontend -lclangDriver -lclangSerialization -lclangParse -lclangSema -lclangAnalysis -lclangEdit -lclangAST -lclangLex -lclangBasic -lclang ${LLVM_LIBS} -ldl -lpthread -lz -lncurses")
SET(LLVM_CFLAGS "${LLVM_CFLAGS} -fno-rtti")
message("LLVM_CFLAGS: " ${LLVM_CFLAGS})
message("LLVM_LDFLAGS: " ${LLVM_LDFLAGS})
message("LLVM_LIBS: " ${LLVM_LIBS})